- platform: darksky
  api_key: !secret dark_sky_api_key
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - temperature
    - cloud_cover
    - visibility
    - temperature_high
    - temperature_low
  
- platform: mqtt
  name: "Yggdrasil soil moisture"
  state_topic: "home/bedroom/avocado/moisture"
  unit_of_measurement: "%"
  icon: "mdi:water"

- platform: mqtt
  name: "Water tank full"
  state_topic: "home/bedroom/avocado/tank"
  icon: "mdi:water"

- platform: time_date
  display_options:
    - 'time'
  
- platform: template
  sensors:
    alarm_clock_hour:
      friendly_name: "Alarm Clock Hour"
      value_template: '{{ states.input_number.alarm_clock_hour.state | int }}'
    alarm_clock_minute:
      friendly_name: "Alarm Clock Minute"
      value_template: '{{ states.input_number.alarm_clock_minute.state | int }}'
    alarm_clock_time:
      friendly_name: "Alarm Clock Time"
      value_template: >-
        {{ states.sensor.alarm_clock_hour.state }}:
        {%- if states.sensor.alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_minute.state }}
    alarm_clock_time_long:
      friendly_name: "Alarm Clock Time"
      value_template: >-
        {%- if states.sensor.alarm_clock_hour.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_hour.state }}:
        {%- if states.sensor.alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_minute.state }}
